---
- hosts: mailservers
  vars:
    account_email: enquiries@karmacomputing.co.uk
    domain: email.pcpink.co.uk
  remote_user: root

  tasks:
  - name: Installl certbot
    apt:
      name: certbot
      state: present

  - name: Get certificate
    shell:
      cmd: certbot certonly --noninteractive --standalone -d {{ domain }} --agree-tos --email {{ account_email }}
